- type: technology
  id: Lightning
  name: next-research-technology-lightning
  icon:
    sprite: Objects/Power/light_bulb.rsi
    state: normal
  discipline: Lightning
  tier: 1
  cost: 500
  recipeUnlocks:
   - LightTube
   - LightBulb

- type: technology
  id: LightningAdvanced
  name: next-research-technology-lightning-advanced
  icon:
    sprite: Objects/Power/light_tube.rsi
    state: normal
  discipline: Lightning
  tier: 1
  cost: 1000
  recipeUnlocks:
   - LedLightTube
   - SodiumLightTube
   - ExteriorLightTube
   - LedLightBulb
   - DimLightBulb
  technologyPrerequisites:
   - Lightning

- type: technology
  id: Bootlegging
  name: next-research-technology-bootlegging
  icon:
    sprite: Objects/Consumable/Drinks/generic_jug.rsi
    state: icon
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
   - DrinkMug
   - DrinkMugMetal
   - DrinkGlass
   - DrinkShotGlass
   - DrinkGlassCoupeShaped
   - CustomDrinkJug

- type: technology
  id: Kitchen
  name: next-research-technology-kitchen
  icon:
    sprite: Objects/Consumable/Food/bowl.rsi
    state: bowl
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
   - FoodPlate
   - FoodPlateSmall
   - FoodPlatePlastic
   - FoodPlateSmallPlastic
   - FoodBowlBig
   - FoodPlateTin
   - FoodPlateMuffinTin
   - FoodKebabSkewer

- type: technology
  id: Hydroponics
  name: next-research-technology-hydroponics
  icon:
    sprite: Objects/Tools/bucket.rsi
    state: icon
  discipline: Lightning
  tier: 1
  cost: 500
  recipeUnlocks:
   - Bucket

- type: technology
  id: Entertainment
  name: next-research-technology-entertainment
  icon:
    sprite: Objects/Fun/Instruments/h_synthesizer.rsi
    state: icon
  discipline: Entertainment
  tier: 1
  cost: 3500
  recipeUnlocks:
   - SynthesizerInstrument
   - HandheldStationMap

- type: technology
  id: FauxAstroTiles
  name: next-research-technology-faux-astro-tiles
  icon:
    sprite: Objects/Tiles/tile.rsi
    state: astroice
  discipline: FauxAstroTiles
  tier: 1
  cost: 5000
  recipeUnlocks:
   - FauxTileAstroGrass
   - FauxTileMowedAstroGrass
   - FauxTileJungleAstroGrass
   - FauxTileAstroIce
   - FauxTileAstroSnow

- type: technology
  id: Cleaning
  name: next-research-technology-cleaning
  icon:
    sprite: Objects/Specific/Janitorial/mop.rsi
    state: mop
  discipline: Cleaning
  tier: 1
  cost: 500
  recipeUnlocks:
   - MopItem
   - TrashBag
   - LightReplacer
   - Holoprojector
   - WetFloorSign
   - ClothingHeadHatCone

- type: technology
  id: CleaningAdvanced
  name: next-research-technology-cleaning-advanced
  icon:
    sprite: Objects/Specific/Janitorial/advmop.rsi
    state: advmop
  discipline: Cleaning
  tier: 1
  cost: 10000
  recipeUnlocks:
   - AdvMopItem
  technologyPrerequisites:
  - Cleaning

- type: technology
  id: Spray
  name: next-research-technology-spray
  icon:
    sprite: Objects/Specific/Janitorial/janitorial.rsi
    state: cleaner
  discipline: Spray
  tier: 1
  cost: 500
  recipeUnlocks:
   - SprayBottle
  technologyPrerequisites:
  - CleaningAdvanced

- type: technology
  id: SprayAdvanced
  name: next-research-technology-spray-advanced
  icon:
    sprite: Objects/Weapons/Guns/Basic/spraynozzle.rsi
    state: icon
  discipline: Spray
  tier: 1
  cost: 10000
  recipeUnlocks:
   - WeaponSprayNozzle
   - ClothingBackpackWaterTank
   - MegaSprayBottle
  technologyPrerequisites:
  - Spray

#- type: technology
#  id: TranslationDevice
#  name: next-research-technology-translation-device
#  icon:
#    sprite: Objects/Devices/translator.rsi
#    state: icon
#  discipline: TranslationDevice
#  tier: 1
#  cost: 10000
#  recipeUnlocks:
#   - BasicGalaticCommonTranslatorImplanter

#- type: technology
#  id: TranslationImplanter
#  name: next-research-technology-translation-implanter
#  icon:
#    sprite: Objects/Specific/Medical/implanter.rsi
#    state: implanter0
#  discipline: TranslationImplanter
#  tier: 1
#  cost: 7500
#  recipeUnlocks:
#   - BasicGalaticCommonTranslatorImplanter
#  technologyPrerequisites:
#  - TranslationDevice

#- type: technology
#  id: TranslationDeviceAdvanced
#  name: next-research-technology-translation-device-advanced
#  icon:
#    sprite: Objects/Devices/translator.rsi
#    state: icon
#  discipline: TranslationDevice
#  tier: 1
#  cost: 12000
#  recipeUnlocks:
#   - XenoTranslator
#   - AnimalTranslator
#  technologyPrerequisites:
#  - CleaningAdvanced

#- type: technology
#  id: TranslationImplanterAdvanced
#  name: next-research-technology-translation-implanter-advanced
#  icon:
#    sprite: Objects/Specific/Medical/implanter.rsi
#    state: implanter0
#  discipline: TranslationImplanter
#  tier: 1
#  cost: 15000
#  recipeUnlocks:
#   - MofficTranslatorImplanter
#   - AdvancedGalaticCommonTranslatorImplanter
#   - BubblishTranslatorImplanter
#   - NekomimeticTranslatorImplanter
#   - DraconicTranslatorImplanter
#   - CanilunztTranslatorImplanter
#   - SolCommonTranslatorImplanter
#   - RootSpeakTranslatorImplanter
#  technologyPrerequisites:
#  - TranslationDevice
#  - TranslationImplanter
#  - TranslationDeviceAdvanced
