- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - Boykisser
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxAstra
  - CorvaxMaus
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxTerra
  - CorvaxPearl
  - CorvaxTushkan
  - Bagel
  - Box
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  #- Train
